### ISSUE TITLE
Authentication issue 

### ISSUE THREAD

**Issue by S-Kanja** [stewartcelani/autodesk-construction-cloud-backup#3]
Hello 

it seems like there is authentication issue 

 System.Net.Http.HttpRequestException: {"developerMessage":"The required parameter(s) client_id,client_secret not present in the request","errorCode":"AUTH-008"

any ideas ? 

thanks

**Comment by stewartcelani** [comment]
It sounds like you have not registered an application with Autodesk and added it to your BIM 360 tenant. You need to pass your own clientid, clientsecret and accountid to ACCBackup at a minimum:

`ACCBackup.exe --backupdirectory "C:\ACCBackup" --clientid "DRO4zxzt71HCkL34cn2tAUSRS0OQGaRT" --clientsecret "tFRHKhuIrGQUi5d3" --accountid "9b3cc923-d920-4fee-ae91-5e9c8e4040rb"`

I have updated the **Prerequities** section of the readme to have clearer instructions to follow to register the application to get these pieces of information. 

Please have a look at that and, if you still are having issues, send your WhatsApp details to github@stewartcelani.com and I can help over chat easier there.

**Comment by S-Kanja** [comment]
Hi, thanks again for the info, i had the application working i have the app keys and secrets all activated and the application registered with BIM360, couple of months ago i notice the app stop working and crashing, further looking into the log i notice the lines i uploaded.. 
i have recreated new keys and having same issue.
tried different pc to make sure its not a client issue, 

did Autodesk make any changes i am missing ? 

any ideas may help, 
thanks
